springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logbook:
  filter:
    enabled: true
  strategy: default
  format:
    style: json

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  pattern:
    level: "%5p [${spring.application.name:-},%X{traceId:-},%X{spanId:-}]"

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics

  observations:
    annotations:
      enabled: true
    sql:
      query-text:
        enabled: true
    key-values:
      db.system: "postgresql"
      db.query.text.enabled: true

  opentelemetry:
    resource-attributes:
      service.name: ${spring.application.name}
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_COLLECTOR_ENDPOINT_HTTP}/v1/traces
          compression: gzip
    logging:
      export:
        otlp:
          endpoint: ${OTEL_COLLECTOR_ENDPOINT_HTTP}/v1/logs

  tracing:
    sampling:
      probability: 1.0

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

  otlp:
    metrics:
      export:
        url: ${OTEL_COLLECTOR_ENDPOINT_HTTP}/v1/metrics
        step: 10s

jdbc:
  datasource-proxy:
    enabled: true
    include-parameter-values: true
  observation:
    enabled: true
    include-query-arguments: true