receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: basic # 改為基本摘要，不顯示詳細內容

  otlp_grpc:
    endpoint: tempo:4317
    tls:
      insecure: true
  
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "spring_boot_4"

  otlp_http/loki:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true

processors:
  batch:
  
  transform:
    log_statements:
      - context: log
        statements:
          - set(attributes["service_name"], resource.attributes["service.name"])
          - set(attributes["app"], resource.attributes["service.name"])

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_grpc]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [transform, batch]
      exporters: [otlp_http/loki] # 移除 debug，僅發送到 Loki