-- V1__init_schema.sql

CREATE TABLE items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255),
    location VARCHAR(255),
    quantity INTEGER NOT NULL,
    min_quantity INTEGER,
    target_quantity INTEGER,
    is_consumable BOOLEAN NOT NULL DEFAULT TRUE,
    status VARCHAR(255) NOT NULL DEFAULT 'ACTIVE',
    last_restocked_at TIMESTAMP,
    version BIGINT,
    note VARCHAR(255),
    image_url VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE inventory_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    type VARCHAR(255) NOT NULL,
    delta_quantity INTEGER NOT NULL,
    before_quantity INTEGER NOT NULL,
    after_quantity INTEGER NOT NULL,
    reason VARCHAR(255),
    source VARCHAR(255) NOT NULL DEFAULT 'MANUAL',
    operator_name VARCHAR(255),
    occurred_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP,
    CONSTRAINT fk_inventory_transactions_item_id FOREIGN KEY (item_id) REFERENCES items (id)
);

CREATE INDEX idx_inventory_transactions_item_id ON inventory_transactions(item_id);

CREATE TABLE shopping_list_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT,
    item_name_snapshot VARCHAR(255) NOT NULL,
    suggested_quantity INTEGER NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    source VARCHAR(255) NOT NULL,
    note VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_shopping_list_items_item_id FOREIGN KEY (item_id) REFERENCES items (id)
);

CREATE INDEX idx_shopping_list_items_item_id ON shopping_list_items(item_id);
