server:
  port: 1031

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: item-service

  config:
    import: "optional:classpath:application-common-lib.yml"

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# 這裡可以只留開發階段特有的 Log 設定 (例如想看 SQL)
logging:
  level:
    org.hibernate.SQL: DEBUG