server:
  port: ${INVENTORY_ITEM_SERVICE_PORT}

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: ${SPRING_APPLICATION_NAME}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  config:
    import: "optional:classpath:application-common-lib.yml"

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${POSTGRES_PORT}/${INVENTORY_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ROOT_USER:minioadmin}
  secret-key: ${MINIO_ROOT_PASSWORD:minioadmin}
  bucket-name: ${MINIO_BUCKET_NAME:inventory-items}
